services:
    Netgen\IbexaFieldTypeHtmlText\OpenGraph\HtmlText:
        parent: netgen_open_graph.handler.field_type.abstract
        tags:
            - { name: netgen_open_graph.meta_tag_handler, alias: field_type/nghtmltext }