parameters:
    ng.fieldtype.html_text.identifier: 'nghtmltext'

services:
    Netgen\IbexaFieldTypeHtmlText\FieldType\Type:
        parent: Ibexa\Core\FieldType\FieldType
        public: true
        tags:
            - { name: ibexa.field_type, alias: '%ng.fieldtype.html_text.identifier%' }

    Netgen\IbexaFieldTypeHtmlText\Persistence\Legacy\FieldValueConverter:
        tags:
            - { name: ibexa.field_type.storage.legacy.converter, alias: '%ng.fieldtype.html_text.identifier%' }

    Netgen\IbexaFieldTypeHtmlText\FieldType\SearchFields:
        tags:
            - { name: ibexa.field_type.indexable, alias: '%ng.fieldtype.html_text.identifier%' }

    Netgen\IbexaFieldTypeHtmlTextBundle\Form\FieldDefinition\FormMapper:
        arguments:
            - '@ibexa.api.service.content_type'
            - '@ibexa.api.service.location'
        tags:
            - { name: ibexa.admin_ui.field_type.form.mapper.definition, fieldType: '%ng.fieldtype.html_text.identifier%' }

    Netgen\IbexaFieldTypeHtmlTextBundle\Form\Field\FieldValueFormMapper:
        arguments:
            - '@ibexa.api.service.content_type'
            - '@ibexa.api.service.location'
        tags:
            - { name: ibexa.admin_ui.field_type.form.mapper.value, fieldType: '%ng.fieldtype.html_text.identifier%' }

    Netgen\IbexaFieldTypeHtmlTextBundle\Form\Field\FieldValueType:
        arguments:
            - '@ibexa.api.service.field_type'
        tags:
            - { name: 'form.type' }
